@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Crypto Legacy SAM API 2.0.+ (2026-06-15)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB937F
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __External public API references__
    *** <back:yellow>**Calypsonet Terminal Reader API**</back>
    *** <back:pink>**Calypsonet Terminal Calypso Card API**</back>
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or error
end legend

package "calypso.crypto.legacysam" as legacysam {

class "LegacySamApiProperties" as ApiProperties <<constants>> <<green>> {
    +const VERSION: String = "2.0"
}
interface "LegacySamApiFactory" as LegacySamApiFactory <<blue>> {

    +createLegacySamSelectionExtension() → LegacySamSelectionExtension

    +createSymmetricCryptoCardTransactionManagerFactory(samReader: <back:yellow>CardReader</back>, sam: LegacySam) → <back:pink>SymmetricCryptoCardTransactionManagerFactory</back>

    +createFreeTransactionManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam) → FreeTransactionManager
    +<color:grey>createSecureReadTransactionManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam, securitySetting: SecuritySetting) → SecureReadTransactionManager
    +createSecureWriteTransactionManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam, securitySetting: SecuritySetting) → SecureWriteTransactionManager
    +createAsyncTransactionCreatorManager(targetSamContext: String, securitySetting: SecuritySetting) → AsyncTransactionCreatorManager
    +createAsyncTransactionExecutorManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam, samCommands: String) → AsyncTransactionExecutorManager
}
enum SystemKeyType <<green>> {
    +PERSONALIZATION
    +KEY_MANAGEMENT
    +RELOADING
    +AUTHENTICATION
}
enum "GetDataTag" as GetDataTag <<green>> {
    +CA_CERTIFICATE
}
enum "CounterIncrementAccess" as CounterIncrementAccess <<green>> {
    +FREE_COUNTING_ENABLED
    +FREE_COUNTING_DISABLED
}

package "transaction" as transaction {
    interface "«<back:yellow>CardTransactionManager</back>»\nTransactionManager" as TransactionManager <<grey>> {
    }
    interface ReadTransactionManager <<grey>> extends TransactionManager {
        +prepareReadSamParameters() → Self

        +<color:grey>prepareReadCaadRecord(caadRecordNumber: Int) → Self
        +<color:grey>prepareReadCaadRecords(fromCaadRecordNumber: Int, toCaadRecordNumber: Int) → Self

        +prepareReadSystemKeyParameters(systemKeyType: SystemKeyType) → Self

        +prepareReadWorkKeyParameters(recordNumber: Int) → Self
        +prepareReadWorkKeyParameters(kif: Byte, kvc: Byte) → Self

        +prepareReadCounterStatus(counterNumber: Int) → Self
        +prepareReadAllCountersStatus() → Self
    }
    interface WriteTransactionManager <<grey>> extends TransactionManager {
        +prepareWriteCounterCeiling(counterNumber: Int, ceilingValue: Int) → Self
        +prepareWriteCounterConfiguration(counterNumber: Int, ceilingValue: Int, counterIncrementAccess: CounterIncrementAccess) → Self
    }
    interface "<color:grey>SecureReadTransactionManager" as SecureReadTransactionManager <<blue>> extends ReadTransactionManager {
    }
    interface FreeTransactionManager <<blue>> extends ReadTransactionManager {
        +prepareGetData(tag: GetDataTag) → Self
        +prepareGenerateCardAsymmetricKeyPair(idCommand: Int) → Self
        +prepareComputeCardCertificate(data: LegacyCardCertificateComputationData, idCommand: Int) → Self

        +<color:grey>preparePlainLoadWorkKey(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, workKeyValue: ByteArray) → Self
        +<color:grey>preparePlainExportWorkKey(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, workKeyValue: ByteArray) → Self

        +preparePlainWriteLock(lockIndex: Byte, lockParameters: Byte, lockValue: ByteArray) → Self

        +prepareComputeSignature(data: SignatureComputationData, idCommand: Int) → Self
        +prepareVerifySignature(data: SignatureVerificationData, idCommand: Int) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SamRevoked</color></size>

        +exportTargetSamContextForAsyncTransaction() → String
    }
    interface "SecureWriteTransactionManager" as SecureWriteTransactionManager <<blue>> extends WriteTransactionManager {
        +prepareWriteSamParameters(parameters: ByteArray) → Self

        +<color:grey>prepareWriteCaadRecord(caadRecordNumber: Int, caad: ByteArray) → Self

        +prepareTransferSystemKey(systemKeyType: SystemKeyType, kvc: Byte, systemKeyParameters: ByteArray) → Self
        +prepareTransferSystemKeyDiversified(systemKeyType: SystemKeyType, kvc: Byte, systemKeyParameters: ByteArray) → Self

        +prepareTransferWorkKey(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, targetRecordNumber: Int) → Self
        +prepareTransferWorkKeyDiversified(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, targetRecordNumber: Int) → Self
        +prepareTransferWorkKeyDiversified(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, targetRecordNumber: Int, diversifier: ByteArray) → Self

        +prepareTransferLock(lockIndex: Byte, lockParameters: Byte) → Self
        +prepareTransferLockDiversified(lockIndex: Byte, lockParameters: Byte) → Self

        +preparePlainWriteLock(lockIndex: Byte, lockParameters: Byte, lockValue: ByteArray) → Self
    }
    interface AsyncTransactionCreatorManager <<blue>> extends WriteTransactionManager {
        +exportCommands() → String
    }
    interface AsyncTransactionExecutorManager <<blue>> extends TransactionManager {
    }

    class "SecuritySetting" as SecuritySetting <<data>> <<green>> {
        +val samReader: <back:yellow>CardReader</back>
        +val controlSam: LegacySam
    }
    interface "«<back:pink>CardTransactionCryptoExtension</back>»\nCardTransactionLegacySamExtension" as CardTransactionLegacySamExtension {
        +prepareComputeSignature(data: SignatureComputationData, idCommand: Int) → Self
        +prepareVerifySignature(data: SignatureVerificationData, idCommand: Int) → Self
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SamRevoked</color></size>
    }

    class "LegacyCardCertificateComputationData" as LegacyCardCertificateComputationData <<data>> <<green>> {
        +val cardPublicKey: ByteArray
        +val startDate: LocalDate
        +val endDate: LocalDate
        +val cardAid: ByteArray
        +val cardSerialNumber: ByteArray
        +val cardStartupInfo: ByteArray
    }

    interface "SignatureComputationData" as SignatureComputationData <<sealed>> {
    }
    class "BasicSignatureComputationData" as BasicSignatureComputationData <<data>> <<green>> implements SignatureComputationData {
        +val data: ByteArray
        +val kif: Byte
        +val kvc: Byte
        +val signatureSize: Int = 8
        +val keyDiversifier: ByteArray? = null
    }
    class "TraceableSignatureComputationData" as TraceableSignatureComputationData <<data>> <<green>> implements SignatureComputationData {
        +val data: ByteArray
        +val kif: Byte
        +val kvc: Byte
        +val signatureSize: Int = 8
        +val keyDiversifier: ByteArray? = null

        +val samTraceabilityMode: SamTraceabilityMode? = null
        +val traceabilityOffset: Int = 0
        +val busyMode: Boolean = true
    }
    enum "SamTraceabilityMode" as SamTraceabilityMode <<green>> {
        +FULL_SERIAL_NUMBER
        +TRUNCATED_SERIAL_NUMBER
    }
    interface "SignatureVerificationData" as SignatureVerificationData <<sealed>> {
    }
    class "BasicSignatureVerificationData" as BasicSignatureVerificationData <<data>> <<green>> implements SignatureVerificationData {
        +val data: ByteArray
        +val signature: ByteArray
        +val kif: Byte
        +val kvc: Byte
        +val keyDiversifier: ByteArray? = null
    }
    class "TraceableSignatureVerificationData" as TraceableSignatureVerificationData <<data>> <<green>> implements SignatureVerificationData {
        +val data: ByteArray
        +val signature: ByteArray
        +val kif: Byte
        +val kvc: Byte
        +val keyDiversifier: ByteArray? = null

        +val samTraceabilityMode: SamTraceabilityMode? = null
        +val traceabilityOffset: Int = 0
        +val samRevocationService: LegacySamRevocationServiceSpi? = null
        +val busyMode: Boolean = true
    }

    ' Errors
    exception "SamRevoked\nInconsistentData\nInvalidSignature" as errors <<error>> <<green>> {
        +val message: String
        +val cause: Any?
    }
}
package "sam" as sam {
    interface "«<back:yellow>CardSelectionExtension</back>»\nLegacySamSelectionExtension" as LegacySamSelectionExtension <<blue>> {
        +setUnlockData(unlockData: String) → Self
        +setUnlockData(unlockData: String, productType: LegacySamProductType) → Self
        +setStaticUnlockDataProvider(staticUnlockDataProvider: LegacySamStaticUnlockDataProviderSpi) → Self
        +setStaticUnlockDataProvider(staticUnlockDataProvider: LegacySamStaticUnlockDataProviderSpi, targetSamReader: CardReader) → Self
        +setDynamicUnlockDataProvider(dynamicUnlockDataProvider: LegacySamDynamicUnlockDataProviderSpi) → Self
        +setDynamicUnlockDataProvider(dynamicUnlockDataProvider: LegacySamDynamicUnlockDataProviderSpi, targetSamReader: CardReader) → Self

        +prepareReadSamParameters() → Self

        +<color:grey>prepareReadCaadRecord(caadRecordNumber: Int) → Self
        +<color:grey>prepareReadCaadRecords(fromCaadRecordNumber: Int, toCaadRecordNumber: Int) → Self

        +prepareReadSystemKeyParameters(systemKeyType: SystemKeyType) → Self

        +prepareReadWorkKeyParameters(recordNumber: Int) → Self
        +prepareReadWorkKeyParameters(kif: Byte, kvc: Byte) → Self

        +prepareReadCounterStatus(counterNumber: Int) → Self
        +prepareReadAllCountersStatus() → Self

        +prepareGetData(tag: GetDataTag) → Self
    }
    interface "«<back:yellow>SmartCard</back>»\nLegacySam" as LegacySam {
        +getProductType() → LegacySamProductType
        +getProductInfo() → String

        +getSerialNumber() → ByteArray
        +getPlatform() → Byte
        +getApplicationType() → Byte
        +getApplicationSubType() → Byte
        +getSoftwareIssuer() → Byte
        +getSoftwareVersion() → Byte
        +getSoftwareRevision() → Byte

        +getCounters() → SortedMap<Int, Int>
        +getCounterCeilings() → SortedMap<Int, Int>
        +<color:blue>getCounterIncrementAccesses() → SortedMap<Int, CounterIncrementAccess>

        +getCaCertificate() → ByteArray?

        +getSamParameters() → ByteArray?

        +getSystemKeyParameter(systemKeyType: SystemKeyType) → KeyParameter?

        +getWorkKeyParameter(recordNumber: Int) → KeyParameter?
        +getWorkKeyParameter(kif: Byte, kvc: Byte) → KeyParameter?

        +<color:blue>getKeyPair(idCommand: Int) → ByteArray?
        +<color:blue>getComputedCardCertificate(idCommand: Int) → ByteArray?
        +<color:blue>getSignature(idCommand: Int) → ByteArray?
        +<color:blue>getSignedData(idCommand: Int) → ByteArray?
        +<color:blue>isSignatureValid(idCommand: Int) → Boolean?
    }
    class "KeyParameter" as KeyParameter <<data>> <<green>> {
        +val rawData: ByteArray
        +val kif: Byte
        +val kvc: Byte
        +val algorithm: Byte
        +val parameterValues: SortedMap<Int, Byte>
    }
    enum "LegacySamProductType" as LegacySamProductType <<green>> {
        +SAM_C1
        +HSM_C1
        +SAM_S1E1
        +SAM_S1DX
        +UNKNOWN
    }
}
package "spi" as spi {
    interface "LegacySamStaticUnlockDataProviderSpi" as LegacySamStaticUnlockDataProviderSpi <<red>> {
        +getUnlockData(samSerialNumber: ByteArray) → ByteArray
    }
    interface "LegacySamDynamicUnlockDataProviderSpi" as LegacySamDynamicUnlockDataProviderSpi <<red>> {
        +getUnlockData(samSerialNumber: ByteArray, samChallenge: ByteArray) → ByteArray
    }
    interface LegacySamRevocationServiceSpi <<red>> {
        +isSamRevoked(serialNumber: ByteArray) → Boolean
        +isSamRevoked(serialNumber: ByteArray, counterValue: Int) → Boolean
    }
}

}

' Associations

TraceableSignatureComputationData ..> SamTraceabilityMode #C_USE : use >

TraceableSignatureVerificationData ...> LegacySamRevocationServiceSpi #C_USE : use >
TraceableSignatureVerificationData ..> SamTraceabilityMode #C_USE : use >

FreeTransactionManager .up.> GetDataTag #C_USE : use >
FreeTransactionManager ..> LegacyCardCertificateComputationData #C_USE : use >
FreeTransactionManager ....> SignatureComputationData #C_USE : use >
FreeTransactionManager ....> SignatureVerificationData #C_USE : use >

ReadTransactionManager .up.> SystemKeyType #C_USE : use >

WriteTransactionManager .up.> CounterIncrementAccess #C_USE : use >

SecureWriteTransactionManager .up..> SystemKeyType #C_USE : use >

CardTransactionLegacySamExtension ..> SignatureComputationData #C_USE : use >
CardTransactionLegacySamExtension ..> SignatureVerificationData #C_USE : use >

LegacySamSelectionExtension ..> LegacySamStaticUnlockDataProviderSpi #C_USE : use >
LegacySamSelectionExtension ..> LegacySamDynamicUnlockDataProviderSpi #C_USE : use >
LegacySamSelectionExtension ..> LegacySamProductType #C_USE : use >
LegacySamSelectionExtension .up.> GetDataTag #C_USE : use >

LegacySam ..> LegacySamProductType #C_LINK : provide >
LegacySam ..> KeyParameter #C_LINK : provide >
LegacySam .up..> SystemKeyType #C_USE : use >
LegacySam .up..> CounterIncrementAccess #C_USE : use >

' == LAYOUT ==

'LegacySamApiFactory -[hidden]- errors
'LegacySamApiFactory -[hidden]right- ApiProperties

' == STYLE ==

package legacysam #C_GREY1 {}
package legacysam.spi #C_GREY2 {}
package legacysam.sam #C_GREY2 {}
package legacysam.transaction #C_GREY2 {}

@enduml