@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Crypto Legacy SAM API 2.0.+ (2026-06-15)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __External public API references__
    *** <back:yellow>**Calypsonet Terminal Reader API**</back>
    *** <back:pink>**Calypsonet Terminal Calypso Card API**</back>
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or error
end legend

package "calypso.crypto.legacysam" as legacysam {

+class "**final** LegacySamApiProperties" as ApiProperties <<green>> {
    +{static} **final** VERSION: String
}
+interface "LegacySamApiFactory" as LegacySamApiFactory <<blue>> {

    +createLegacySamSelectionExtension() → LegacySamSelectionExtension

    +createSymmetricCryptoCardTransactionManagerFactory(samReader: <back:yellow>CardReader</back>, sam: LegacySam) → <back:pink>SymmetricCryptoCardTransactionManagerFactory</back>

    +createSecuritySetting() → SecuritySetting

    +createFreeTransactionManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam) → FreeTransactionManager
    +<color:grey>createSecureReadTransactionManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam, securitySetting: SecuritySetting) → SecureReadTransactionManager
    +createSecureWriteTransactionManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam, securitySetting: SecuritySetting) → SecureWriteTransactionManager
    +createAsyncTransactionCreatorManager(targetSamContext: String, securitySetting: SecuritySetting) → AsyncTransactionCreatorManager
    +createAsyncTransactionExecutorManager(samReader: <back:yellow>CardReader</back>, sam: LegacySam, samCommands: String) → AsyncTransactionExecutorManager

    +createKeyPairContainer() → KeyPairContainer
    +createLegacyCardCertificateComputationData() → LegacyCardCertificateComputationData

    +createBasicSignatureComputationData() → BasicSignatureComputationData
    +createTraceableSignatureComputationData() → TraceableSignatureComputationData
    +createBasicSignatureVerificationData() → BasicSignatureVerificationData
    +createTraceableSignatureVerificationData() → TraceableSignatureVerificationData
}
+enum SystemKeyType <<green>> {
    PERSONALIZATION
    KEY_MANAGEMENT
    RELOADING
    AUTHENTICATION
}
+enum "GetDataTag" as GetDataTag <<green>> {
    CA_CERTIFICATE
}
+enum "CounterIncrementAccess" as CounterIncrementAccess <<green>> {
    FREE_COUNTING_ENABLED
    FREE_COUNTING_DISABLED
}

package "transaction" as transaction {
    +interface "<<<back:yellow>CardTransactionManager</back>>></color>\nTransactionManager" as TransactionManager <<grey>> {
    }
    +interface ReadTransactionManager<T : ReadTransactionManager<T>> <<grey>> extends TransactionManager {
        +prepareReadSamParameters() → T

        +<color:grey>prepareReadCaadRecord(caadRecordNumber: Int) → T
        +<color:grey>prepareReadCaadRecords(fromCaadRecordNumber: Int, toCaadRecordNumber: Int) → T

        +prepareReadSystemKeyParameters(systemKeyType: SystemKeyType) → T

        +prepareReadWorkKeyParameters(recordNumber: Int) → T
        +prepareReadWorkKeyParameters(kif: Byte, kvc: Byte) → T

        +prepareReadCounterStatus(counterNumber: Int) → T
        +prepareReadAllCountersStatus() → T
    }
    +interface WriteTransactionManager<T : WriteTransactionManager<T>> <<grey>> extends TransactionManager {
        +prepareWriteCounterCeiling(counterNumber: Int, ceilingValue: Int) → T
        +prepareWriteCounterConfiguration(counterNumber: Int, ceilingValue: Int, counterIncrementAccess: CounterIncrementAccess) → T
    }
    +interface "<color:grey>SecureReadTransactionManager" as SecureReadTransactionManager <<blue>> extends ReadTransactionManager {
    }
    +interface FreeTransactionManager <<blue>> extends ReadTransactionManager {
        +prepareGetData(tag: GetDataTag) → FreeTransactionManager
        +prepareGenerateCardAsymmetricKeyPair(keyPairContainer: KeyPairContainer) → FreeTransactionManager
        +prepareComputeCardCertificate(data: LegacyCardCertificateComputationData) → FreeTransactionManager

        +<color:grey>preparePlainLoadWorkKey(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, workKeyValue: ByteArray) → FreeTransactionManager
        +<color:grey>preparePlainExportWorkKey(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, workKeyValue: ByteArray) → FreeTransactionManager

        +preparePlainWriteLock(lockIndex: Byte, lockParameters: Byte, lockValue: ByteArray) → FreeTransactionManager

        +prepareComputeSignature(data: SignatureComputationData<?>) → FreeTransactionManager
        +prepareVerifySignature(data: SignatureVerificationData<?>) → FreeTransactionManager
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SamRevoked</color></size>

        +exportTargetSamContextForAsyncTransaction() → String
    }
    +interface "SecureWriteTransactionManager" as SecureWriteTransactionManager <<blue>> extends WriteTransactionManager {
        +prepareWriteSamParameters(parameters: ByteArray) → SecureWriteTransactionManager

        +<color:grey>prepareWriteCaadRecord(caadRecordNumber: Int, caad: ByteArray) → SecureWriteTransactionManager

        +prepareTransferSystemKey(systemKeyType: SystemKeyType, kvc: Byte, systemKeyParameters: ByteArray) → SecureWriteTransactionManager
        +prepareTransferSystemKeyDiversified(systemKeyType: SystemKeyType, kvc: Byte, systemKeyParameters: ByteArray) → SecureWriteTransactionManager

        +prepareTransferWorkKey(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, targetRecordNumber: Int) → SecureWriteTransactionManager
        +prepareTransferWorkKeyDiversified(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, targetRecordNumber: Int) → SecureWriteTransactionManager
        +prepareTransferWorkKeyDiversified(kif: Byte, kvc: Byte, workKeyParameters: ByteArray, targetRecordNumber: Int, diversifier: ByteArray) → SecureWriteTransactionManager

        +prepareTransferLock(lockIndex: Byte, lockParameters: Byte) → SecureWriteTransactionManager
        +prepareTransferLockDiversified(lockIndex: Byte, lockParameters: Byte) → SecureWriteTransactionManager

        +preparePlainWriteLock(lockIndex: Byte, lockParameters: Byte, lockValue: ByteArray) → SecureWriteTransactionManager
    }
    +interface AsyncTransactionCreatorManager <<blue>> extends WriteTransactionManager {
        +exportCommands() → String
    }
    +interface AsyncTransactionExecutorManager <<blue>> extends TransactionManager {
    }

    +interface SecuritySetting <<blue>> {
        +setControlSamResource(samReader: <back:yellow>CardReader</back>, controlSam: LegacySam) → SecuritySetting
    }
    +interface "<<<back:pink>CardTransactionCryptoExtension</back>>>\nCardTransactionLegacySamExtension" as CardTransactionLegacySamExtension {
        +prepareComputeSignature(data: SignatureComputationData<?>) → CardTransactionLegacySamExtension
        +prepareVerifySignature(data: SignatureVerificationData<?>) → CardTransactionLegacySamExtension
        {method} <size:10><color:#7F8C8D>    ⚠ errors: SamRevoked</color></size>
    }

    +interface "KeyPairContainer" as KeyPairContainer <<blue>> {
        +getKeyPair() → ByteArray
    }
    +interface "LegacyCardCertificateComputationData" as LegacyCardCertificateComputationData <<blue>> {
        +setCardPublicKey(cardPublicKey: ByteArray) → LegacyCardCertificateComputationData
        +setStartDate(startDate: LocalDate) → LegacyCardCertificateComputationData
        +setEndDate(endDate: LocalDate) → LegacyCardCertificateComputationData
        +setCardAid(aid: ByteArray) → LegacyCardCertificateComputationData
        +setCardSerialNumber(serialNumber: ByteArray) → LegacyCardCertificateComputationData
        +setCardStartupInfo(startupInfo: ByteArray) → LegacyCardCertificateComputationData

        +getCertificate() → ByteArray?
    }

    +interface "SignatureComputationData" as SignatureComputationData<T : SignatureComputationData<T>> <<grey>> {
        +setData(data: ByteArray, kif: Byte, kvc: Byte) → T
        +setSignatureSize(size: Int) → T
        +setKeyDiversifier(diversifier: ByteArray) → T

        +getSignature() → ByteArray
    }
    +interface BasicSignatureComputationData <<blue>> extends SignatureComputationData {
    }
    +interface TraceableSignatureComputationData <<blue>> extends SignatureComputationData {
        +withSamTraceabilityMode(offset: Int, samTraceabilityMode: SamTraceabilityMode) → TraceableSignatureComputationData
        +withoutBusyMode() → TraceableSignatureComputationData

        +getSignedData() → ByteArray
    }
    +enum "SamTraceabilityMode" as SamTraceabilityMode <<green>> {
        FULL_SERIAL_NUMBER
        TRUNCATED_SERIAL_NUMBER
    }
    +interface "SignatureVerificationData" as SignatureVerificationData<T : SignatureVerificationData<T>> <<grey>> {
        +setData(data: ByteArray, signature: ByteArray, kif: Byte, kvc: Byte) → T
        +setKeyDiversifier(diversifier: ByteArray) → T

        +isSignatureValid() → Boolean
    }
    +interface BasicSignatureVerificationData <<blue>> extends SignatureVerificationData {
    }
    +interface TraceableSignatureVerificationData <<blue>> extends SignatureVerificationData {
        +withSamTraceabilityMode(offset: Int, samTraceabilityMode: SamTraceabilityMode, samRevocationService: LegacySamRevocationServiceSpi) → TraceableSignatureVerificationData
        +withoutBusyMode() → TraceableSignatureVerificationData
    }

    ' Errors
    +exception "<i>«error»\nSamRevoked\nInconsistentData\nInvalidSignature" as errors <<purple>>  {
        +val message: String
        +val cause: Any?
    }
}
package "sam" as sam {
    +interface "<<<back:yellow>CardSelectionExtension</back>>>\nLegacySamSelectionExtension" as LegacySamSelectionExtension <<blue>> {
        +setUnlockData(unlockData: String) → LegacySamSelectionExtension
        +setUnlockData(unlockData: String, productType: LegacySam.ProductType) → LegacySamSelectionExtension
        +setStaticUnlockDataProvider(staticUnlockDataProvider: LegacySamStaticUnlockDataProviderSpi) → LegacySamSelectionExtension
        +setStaticUnlockDataProvider(staticUnlockDataProvider: LegacySamStaticUnlockDataProviderSpi, targetSamReader: CardReader) → LegacySamSelectionExtension
        +setDynamicUnlockDataProvider(dynamicUnlockDataProvider: LegacySamDynamicUnlockDataProviderSpi) → LegacySamSelectionExtension
        +setDynamicUnlockDataProvider(dynamicUnlockDataProvider: LegacySamDynamicUnlockDataProviderSpi, targetSamReader: CardReader) → LegacySamSelectionExtension

        +prepareReadSamParameters() → LegacySamSelectionExtension

        +<color:grey>prepareReadCaadRecord(caadRecordNumber: Int) → LegacySamSelectionExtension
        +<color:grey>prepareReadCaadRecords(fromCaadRecordNumber: Int, toCaadRecordNumber: Int) → LegacySamSelectionExtension

        +prepareReadSystemKeyParameters(systemKeyType: SystemKeyType) → LegacySamSelectionExtension

        +prepareReadWorkKeyParameters(recordNumber: Int) → LegacySamSelectionExtension
        +prepareReadWorkKeyParameters(kif: Byte, kvc: Byte) → LegacySamSelectionExtension

        +prepareReadCounterStatus(counterNumber: Int) → LegacySamSelectionExtension
        +prepareReadAllCountersStatus() → LegacySamSelectionExtension

        +prepareGetData(tag: GetDataTag) → LegacySamSelectionExtension
    }
    +interface "<<<back:yellow>SmartCard</back>>>\nLegacySam" as LegacySam {
        +getProductType() → ProductType
        +getProductInfo() → String

        +getSerialNumber() → ByteArray
        +getPlatform() → Byte
        +getApplicationType() → Byte
        +getApplicationSubType() → Byte
        +getSoftwareIssuer() → Byte
        +getSoftwareVersion() → Byte
        +getSoftwareRevision() → Byte

        +getCounter(counterNumber: Int) → Int?
        +getCounters() → SortedMap<Int, Int>
        +getCounterIncrementAccess(counterNumber: Int) → CounterIncrementAccess?

        +getCounterCeiling(counterNumber: Int) → Int?
        +getCounterCeilings() → SortedMap<Int, Int>

        +getCaCertificate() → ByteArray?

        +getSamParameters() → SamParameters?

        +getSystemKeyParameter(systemKeyType: SystemKeyType) → KeyParameter?

        +getWorkKeyParameter(recordNumber: Int) → KeyParameter?
        +getWorkKeyParameter(kif: Byte, kvc: Byte) → KeyParameter?
    }
    +interface "SamParameters" as SamParameters {
        +getRawData() → ByteArray
    }
    +interface KeyParameter {
        +getRawData() → ByteArray
        +getKif() → Byte
        +getKvc() → Byte
        +getAlgorithm() → Byte
        +getParameterValue(parameterNumber: Int) → Byte
    }
    +enum "ProductType" as SamProductType <<green>> {
        SAM_C1
        HSM_C1
        SAM_S1E1
        SAM_S1Dx
        UNKNOWN
    }
}
package "spi" as spi {
    +interface "LegacySamStaticUnlockDataProviderSpi" as LegacySamStaticUnlockDataProviderSpi <<red>> {
        +getUnlockData(samSerialNumber: ByteArray) → ByteArray
    }
    +interface "LegacySamDynamicUnlockDataProviderSpi" as LegacySamDynamicUnlockDataProviderSpi <<red>> {
        +getUnlockData(samSerialNumber: ByteArray, samChallenge: ByteArray) → ByteArray
    }
    +interface LegacySamRevocationServiceSpi <<red>> {
        +isSamRevoked(serialNumber: ByteArray) → Boolean
        +isSamRevoked(serialNumber: ByteArray, counterValue: Int) → Boolean
    }
}

}

' Associations

TraceableSignatureComputationData ..> SamTraceabilityMode #C_USE : use >

TraceableSignatureVerificationData ...> LegacySamRevocationServiceSpi #C_USE : use >
TraceableSignatureVerificationData ..> SamTraceabilityMode #C_USE : use >

FreeTransactionManager .up.> GetDataTag #C_USE : use >
FreeTransactionManager ..> KeyPairContainer #C_USE : use >
FreeTransactionManager ..> LegacyCardCertificateComputationData #C_USE : use >
FreeTransactionManager ....> SignatureComputationData #C_USE : use >
FreeTransactionManager ....> SignatureVerificationData #C_USE : use >

ReadTransactionManager .up.> SystemKeyType #C_USE : use >

WriteTransactionManager .up.> CounterIncrementAccess #C_USE : use >

SecureWriteTransactionManager .up..> SystemKeyType #C_USE : use >

CardTransactionLegacySamExtension ..> SignatureComputationData #C_USE : use >
CardTransactionLegacySamExtension ..> SignatureVerificationData #C_USE : use >

LegacySamSelectionExtension ..> LegacySamStaticUnlockDataProviderSpi #C_USE : use >
LegacySamSelectionExtension ..> LegacySamDynamicUnlockDataProviderSpi #C_USE : use >
LegacySamSelectionExtension ..> SamProductType #C_USE : use >
LegacySamSelectionExtension .up.> GetDataTag #C_USE : use >

LegacySam +-- SamProductType
LegacySam ..> SamProductType #C_LINK : provide >
LegacySam ..> SamParameters #C_LINK : provide >
LegacySam ..> KeyParameter #C_LINK : provide >
LegacySam .up..> SystemKeyType #C_USE : use >
LegacySam .up..> CounterIncrementAccess #C_LINK : provide >

' == LAYOUT ==

'LegacySamApiFactory -[hidden]- errors
'LegacySamApiFactory -[hidden]right- ApiProperties

' == STYLE ==

package legacysam #C_GREY1 {}
package legacysam.spi #C_GREY2 {}
package legacysam.sam #C_GREY2 {}
package legacysam.transaction #C_GREY2 {}

@enduml