@startuml
title
    Calypsonet - calypsonet-terminal-calypso-crypto-legacysam-java-api - 0.1.+ (2022-10-27) v2
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External public API references__ :
    ** <back:yellow>**calypsonet-terminal-reader-java-api**</back>
    ** <back:pink>**calypsonet-terminal-calypso-java-api**</back>
end legend

package "org.calypsonet.terminal.calypso.sam.legacy" as api {
    +class "**final** LegacySamApiProperties" as ApiProperties {
        +{static} **final** String VERSION
    }
    +interface "<<<back:pink>CalypsoLegacySam</back>>>\nLegacySam" as LegacySam {
        +Integer getEventCounter (int eventCounterNumber)
        +SortedMap<Integer, Integer> getEventCounters ()

        +Integer getEventCeiling (int eventCeilingNumber)
        +SortedMap<Integer, Integer> getEventCeilings ()
    }
    +interface LegacySamSecuritySetting {
        +LegacySamSecuritySetting setControlSamResource (<back:yellow>CardReader</back> samReader, LegacySam calypsoSam)
    }
    +interface LegacySamTransactionManager<T extends LegacySamTransactionManager<T>> {
        +<back:yellow>CardReader</back> getSamReader ()
        +LegacySam getCalypsoSam ()
        +List<byte[]> getTransactionAuditData ()
        +T processCommands ()
    }
    +interface LegacySamSecureTransactionManager<T extends LegacySamSecureTransactionManager<T>> extends LegacySamTransactionManager {
        +LegacySamSecuritySetting getSecuritySetting ()
    }
    +interface LegacySamFreeTransactionManager extends LegacySamTransactionManager {
        +LegacySamFreeTransactionManager prepareComputeSignature (CommonSignatureComputationData<?> data)
        +LegacySamFreeTransactionManager prepareVerifySignature (CommonSignatureVerificationData<?> data)

        +LegacySamFreeTransactionManager prepareReadSamParameters ()

        +LegacySamFreeTransactionManager prepareReadCaadRecord (int caadRecordNumber)
        +LegacySamFreeTransactionManager prepareReadCaadRecords (int fromCaadRecordNumber, int toCaadRecordNumber)

        +LegacySamFreeTransactionManager prepareReadSystemKeyParameters (LegacySystemKey systemKey)

        +LegacySamFreeTransactionManager prepareReadWorkKeyParameter (int workKeyRecordNumber)
        +LegacySamFreeTransactionManager prepareReadWorkKeyParameters (int fromWorkKeyRecordNumber, int toWorkKeyRecordNumber)

        +LegacySamFreeTransactionManager prepareReadWorkKeyParameter (byte workKeyKif, byte workKeyKvc)

        +LegacySamFreeTransactionManager prepareReadEventCounter (int eventCounterNumber)
        +LegacySamFreeTransactionManager prepareReadEventCounters (int fromEventCounterNumber, int toEventCounterNumber)

        +LegacySamFreeTransactionManager prepareReadEventCeiling (int eventCeilingNumber)
        +LegacySamFreeTransactionManager prepareReadEventCeilings (int fromEventCeilingNumber, int toEventCeilingNumber)

        +LegacySamFreeTransactionManager prepareWriteExternalPlainWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters, byte[] workKeyValue)
        +LegacySamFreeTransactionManager prepareWriteRandomlyGeneratedWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters)
    }
    +interface LegacySamSecureReadTransactionManager extends LegacySamSecureTransactionManager {
        +LegacySamSecureReadTransactionManager prepareReadSamParameters ()

        +LegacySamSecureReadTransactionManager prepareReadCaadRecord (int caadRecordNumber)
        +LegacySamSecureReadTransactionManager prepareReadCaadRecords (int fromCaadRecordNumber, int toCaadRecordNumber)

        +LegacySamSecureReadTransactionManager prepareReadSystemKeyParameters (LegacySystemKey systemKey)

        +LegacySamSecureReadTransactionManager prepareReadWorkKeyParameter (int workKeyRecordNumber)
        +LegacySamSecureReadTransactionManager prepareReadWorkKeyParameters (int fromWorkKeyRecordNumber, int toWorkKeyRecordNumber)

        +LegacySamSecureReadTransactionManager prepareReadWorkKeyParameter (byte workKeyKif, byte workKeyKvc)

        +LegacySamSecureReadTransactionManager prepareReadEventCounter (int eventCounterNumber)
        +LegacySamSecureReadTransactionManager prepareReadEventCounters (int fromEventCounterNumber, int toEventCounterNumber)

        +LegacySamSecureReadTransactionManager prepareReadEventCeiling (int eventCeilingNumber)
        +LegacySamSecureReadTransactionManager prepareReadEventCeilings (int fromEventCeilingNumber, int toEventCeilingNumber)
    }
    +interface LegacySamSecureWriteTransactionManager extends LegacySamSecureTransactionManager {
        +LegacySamSecureWriteTransactionManager prepareWriteExternalPlainWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters, byte[] workKeyValue)
        +LegacySamSecureWriteTransactionManager prepareWriteRandomlyGeneratedWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters)

        +LegacySamSecureWriteTransactionManager prepareWriteSamParameters (byte[] parameters)
        +LegacySamSecureWriteTransactionManager prepareWriteCaadRecord (int caadRecordNumber, byte[] caad)

        +LegacySamSecureWriteTransactionManager prepareWriteTransferredCipheredSystemKey (LegacySystemKey sourceSystemKey, byte sourceSystemKeyKif, byte sourceSystemKeyKvc)
        +LegacySamSecureWriteTransactionManager prepareWriteTransferredPlainWorkKey (byte sourceWorkKeyKif, byte sourceWorkKeyKvc, byte[] workKeyParameters)
        +LegacySamSecureWriteTransactionManager prepareWriteTransferredCipheredWorkKey (byte sourceWorkKeyKif, byte sourceWorkKeyKvc, byte[] workKeyParameters, byte cipheringSystemKeyKvc)

        +LegacySamSecureWriteTransactionManager prepareWriteEventCeiling (int eventCeilingNumber, int newValue)
        +LegacySamSecureWriteTransactionManager prepareWriteEventCeilings (int fromEventCeilingNumber, List<Integer> newValues)
    }
    +interface LegacyTargetSamStaticTransactionManager extends LegacySamTransactionManager {
        +LegacyTargetSamStaticTransactionManager importCommands (String cipheredSamCommands)
    }
    +interface LegacyControlSamStaticTransactionManager extends LegacySamTransactionManager {
        +LegacyControlSamStaticTransactionManager prepareWriteExternalPlainWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters, byte[] workKeyValue)
        +LegacyControlSamStaticTransactionManager prepareWriteRandomlyGeneratedWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters)

        +LegacyControlSamStaticTransactionManager prepareWriteSamParameters (byte[] parameters)
        +LegacyControlSamStaticTransactionManager prepareWriteCaadRecord (int caadRecordNumber, byte[] caad)

        +LegacyControlSamStaticTransactionManager prepareWriteTransferredCipheredSystemKey (LegacySystemKey sourceSystemKey, byte sourceSystemKeyKif, byte sourceSystemKeyKvc)
        +LegacyControlSamStaticTransactionManager prepareWriteTransferredPlainWorkKey (byte sourceWorkKeyKif, byte sourceWorkKeyKvc, byte[] workKeyParameters)
        +LegacyControlSamStaticTransactionManager prepareWriteTransferredCipheredWorkKey (byte sourceWorkKeyKif, byte sourceWorkKeyKvc, byte[] workKeyParameters, byte cipheringSystemKeyKvc)

        +LegacyControlSamStaticTransactionManager prepareWriteEventCeiling (int eventCeilingNumber, int newValue)
        +LegacyControlSamStaticTransactionManager prepareWriteEventCeilings (int fromEventCeilingNumber, List<Integer> newValues)

        +LegacyControlSamStaticTransactionManager prepareGiveTargetSamPseudoRandom (? staticRandom)

        +String exportCommands ()
    }
}

' Associations

LegacySamTransactionManager .right.> LegacySam #C_LINK : provide >

LegacySamSecureTransactionManager .up.> LegacySamSecuritySetting #C_LINK : provide >

' == LAYOUT ==

interface LegacySam <<purple>>

interface LegacySamSecuritySetting <<purple>>

' == STYLE ==

package api #C_GREY1 {}


@enduml