@startuml
title
    Calypsonet - calypsonet-terminal-calypso-crypto-legacysam-java-api - 0.1.+ (2022-11-29) v3 FULL
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External public API references__ :
    ** <back:yellow>**calypsonet-terminal-reader-java-api**</back>
    ** <back:pink>**calypsonet-terminal-calypso-java-api**</back>
end legend

package "org.calypsonet.terminal.calypso.crypto.symmetric.legacysam" as api {
    +class "**final** LegacySamApiProperties" as ApiProperties {
        +{static} **final** String VERSION
    }
    +interface "<<<back:pink>CardTransactionCryptoExtension</back>>>\nLegacySamCardTransactionCryptoExtension" as LegacySamCardTransactionCryptoExtension {
        +LegacySamCardTransactionCryptoExtension prepareComputeSignature (CommonSignatureComputationData<?> data)
        +LegacySamCardTransactionCryptoExtension prepareVerifySignature (CommonSignatureVerificationData<?> data)
    }
    +interface LegacySamTransactionManagerFactory {
        +LegacySamFreeTransactionManager createFreeTransactionManager (<back:yellow>CardReader</back> samReader, LegacySam sam)
        +LegacySamSecureReadTransactionManager createSecureReadTransactionManager (<back:yellow>CardReader</back> samReader, LegacySam sam, LegacySamSecuritySetting securitySetting)
        +LegacySamSecureWriteTransactionManager createSecureWriteTransactionManager (<back:yellow>CardReader</back> samReader, LegacySam sam, LegacySamSecuritySetting securitySetting)
        +LegacyControlSamStaticTransactionManager createControlSamStaticTransactionManager (<back:yellow>CardReader</back> samReader, LegacySam sam)
        +LegacyTargetSamStaticTransactionManager createTargetSamStaticTransactionManager (<back:yellow>CardReader</back> samReader, LegacySam sam)
    }
    +interface LegacySamTransactionManager<T extends LegacySamTransactionManager<T>> {
        +List<byte[]> getTransactionAuditData ()
        +T processCommands ()
    }
    +interface LegacySamReadTransactionManager<T extends LegacySamReadTransactionManager<T>> extends LegacySamTransactionManager {
        +T prepareReadSamParameters ()

        +T prepareReadCaadRecord (int caadRecordNumber)
        +T prepareReadCaadRecords (int fromCaadRecordNumber, int toCaadRecordNumber)

        +T prepareReadSystemKeyParameters (LegacySystemKey systemKey)

        +T prepareReadWorkKeyParameter (int workKeyRecordNumber)
        +T prepareReadWorkKeyParameters (int fromWorkKeyRecordNumber, int toWorkKeyRecordNumber)

        +T prepareReadWorkKeyParameter (byte workKeyKif, byte workKeyKvc)

        +T prepareReadEventCounter (int eventCounterNumber)
        +T prepareReadEventCounters (int fromEventCounterNumber, int toEventCounterNumber)

        +T prepareReadEventCeiling (int eventCeilingNumber)
        +T prepareReadEventCeilings (int fromEventCeilingNumber, int toEventCeilingNumber)
    }
    +interface LegacySamFreeWriteTransactionManager<T extends LegacySamFreeWriteTransactionManager<T>> extends LegacySamTransactionManager {
        +T prepareWriteExternalPlainWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters, byte[] workKeyValue)
        +T prepareWriteRandomlyGeneratedWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters)
    }
    +interface LegacySamWriteTransactionManager<T extends LegacySamWriteTransactionManager<T>> extends LegacySamFreeWriteTransactionManager {
        +T prepareWriteExternalPlainWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters, byte[] workKeyValue)
        +T prepareWriteRandomlyGeneratedWorkKey (byte workKeyKif, byte workKeyKvc, byte[] workKeyParameters)

        +T prepareWriteSamParameters (byte[] parameters)
        +T prepareWriteCaadRecord (int caadRecordNumber, byte[] caad)

        +T prepareWriteTransferredCipheredSystemKey (LegacySystemKey sourceSystemKey, byte sourceSystemKeyKif, byte sourceSystemKeyKvc)
        +T prepareWriteTransferredPlainWorkKey (byte sourceWorkKeyKif, byte sourceWorkKeyKvc, byte[] workKeyParameters)
        +T prepareWriteTransferredCipheredWorkKey (byte sourceWorkKeyKif, byte sourceWorkKeyKvc, byte[] workKeyParameters, byte cipheringSystemKeyKvc)

        +T prepareWriteEventCeiling (int eventCeilingNumber, int newValue)
        +T prepareWriteEventCeilings (int fromEventCeilingNumber, List<Integer> newValues)
    }
    together {
        +interface LegacySamSecureReadTransactionManager extends LegacySamReadTransactionManager {
        }
        +interface LegacySamFreeTransactionManager extends LegacySamReadTransactionManager, LegacySamFreeWriteTransactionManager {
            +LegacySamFreeTransactionManager prepareComputeSignature (CommonSignatureComputationData<?> data)
            +LegacySamFreeTransactionManager prepareVerifySignature (CommonSignatureVerificationData<?> data)
        }
        +interface LegacySamSecureWriteTransactionManager extends LegacySamWriteTransactionManager {
        }
        +interface LegacyTargetSamStaticTransactionManager extends LegacySamTransactionManager {
            +LegacyTargetSamStaticTransactionManager importCommands (String cipheredSamCommands)
        }
        +interface LegacyControlSamStaticTransactionManager extends LegacySamWriteTransactionManager {
            +LegacyControlSamStaticTransactionManager prepareGiveTargetSamPseudoRandom (? staticRandom)
            +String exportCommands ()
        }
    }
    package sam {
        +interface "<<<back:yellow>CardSelection</back>>>\nLegacySamSelection" as LegacySamSelection {
            +LegacySamSelection filterByProductType (LegacySam.ProductType productType)
            +LegacySamSelection filterBySerialNumber (String serialNumberRegex)

            +LegacySamSelection setUnlockData (String unlockData)
        }
        +interface "<<<back:yellow>SmartCard</back>>>\nLegacySam" as LegacySam {
            +ProductType getProductType ()
            +String getProductInfo ()

            +byte[] getSerialNumber ()
            +byte getPlatform ()
            +byte getApplicationType ()
            +byte getApplicationSubType ()
            +byte getSoftwareIssuer ()
            +byte getSoftwareVersion ()
            +byte getSoftwareRevision ()

            +Integer getEventCounter (int eventCounterNumber)
            +SortedMap<Integer, Integer> getEventCounters ()

            +Integer getEventCeiling (int eventCeilingNumber)
            +SortedMap<Integer, Integer> getEventCeilings ()
        }
        +enum "ProductType" as SamProductType {
            SAM_C1
            HSM_C1
            SAM_S1E1
            SAM_S1Dx
            CSAM_F
            UNKNOWN
        }
    }
    +interface LegacySamSecuritySetting {
        +LegacySamSecuritySetting setControlSamResource (<back:yellow>CardReader</back> samReader, LegacySam sam)
        +LegacySamSecuritySetting setSamRevocationServiceSpi (SamRevocationServiceSpi service)
    }
    package spi {
        +interface SamRevocationServiceSpi {
            +boolean isSamRevoked (byte[] serialNumber)
            +boolean isSamRevoked (byte[] serialNumber, int counterValue)
        }
    }
    +interface CommonSignatureComputationData<T extends CommonSignatureComputationData<T>> {
        +T setData (byte[] data, byte kif, byte kvc)
        +T setSignatureSize (int size)
        +T setKeyDiversifier (byte[] diversifier)

        +byte[] getSignature ()
    }
    +interface BasicSignatureComputationData extends CommonSignatureComputationData {
    }
    +interface TraceableSignatureComputationData extends CommonSignatureComputationData {
        +TraceableSignatureComputationData withSamTraceabilityMode (int offset, boolean usePartialSamSerialNumber)
        +TraceableSignatureComputationData withoutBusyMode ()

        +byte[] getSignedData ()
    }
    +interface CommonSignatureVerificationData<T extends CommonSignatureVerificationData<T>> {
        +T setData (byte[] data, byte[] signature, byte kif, byte kvc)
        +T setKeyDiversifier (byte[] diversifier)

        +boolean isSignatureValid ()
    }
    +interface BasicSignatureVerificationData extends CommonSignatureVerificationData {
    }
    +interface TraceableSignatureVerificationData extends CommonSignatureVerificationData {
        +TraceableSignatureVerificationData withSamTraceabilityMode (int offset, boolean isPartialSamSerialNumber, boolean checkSamRevocationStatus)
        +TraceableSignatureVerificationData withoutBusyMode ()
    }
}

' Associations

LegacySamTransactionManagerFactory .up.> LegacySamSecureReadTransactionManager #C_LINK : provide >
LegacySamTransactionManagerFactory .up.> LegacySamFreeTransactionManager #C_LINK : provide >
LegacySamTransactionManagerFactory .up.> LegacySamSecureWriteTransactionManager #C_LINK : provide >
LegacySamTransactionManagerFactory .up.> LegacyControlSamStaticTransactionManager #C_LINK : provide >
LegacySamTransactionManagerFactory .up.> LegacyTargetSamStaticTransactionManager #C_LINK : provide >
LegacySamTransactionManagerFactory ..> LegacySam #C_USE : use >
LegacySamTransactionManagerFactory ..> LegacySamSecuritySetting #C_USE : use >

LegacySamSecuritySetting ..> SamRevocationServiceSpi #C_USE : use >

LegacySamFreeTransactionManager ..> CommonSignatureComputationData #C_USE : use >
LegacySamFreeTransactionManager ..> CommonSignatureVerificationData #C_USE : use >

LegacySamCardTransactionCryptoExtension ..> CommonSignatureComputationData #C_USE : use >
LegacySamCardTransactionCryptoExtension ..> CommonSignatureVerificationData #C_USE : use >

LegacySamSelection ..> SamProductType #C_USE : use >

LegacySam +-- SamProductType
LegacySam ..> SamProductType #C_LINK : provide >

' == LAYOUT ==



' == STYLE ==

package api #C_GREY1 {}
package spi #C_GREY2 {}
package sam #C_GREY2 {}

interface LegacySamSelection <<purple>>
interface LegacySam <<purple>>
interface SamProductType <<purple>>
interface LegacySamSecuritySetting <<purple>>
interface CommonSignatureComputationData <<purple>>
interface BasicSignatureComputationData <<purple>>
interface TraceableSignatureComputationData <<purple>>
interface CommonSignatureVerificationData <<purple>>
interface BasicSignatureVerificationData <<purple>>
interface TraceableSignatureVerificationData <<purple>>

interface LegacySamTransactionManagerFactory <<red>>
interface LegacySamCardTransactionCryptoExtension <<green>>

@enduml